2022-04-05 01:36:25,658 ERROR: Exception on /index [GET] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/mrprogg/flask/microblog1/app/routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/mrprogg/flask/microblog1/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 5, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-05 01:38:57,616 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 01:40:50,123 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 02:05:59,294 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
