2022-04-03 17:09:33,408 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:14:09,927 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:14:39,220 ERROR: Exception on /edit_profile [POST] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2022-04-03 17:21:41,797 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:21:47,364 ERROR: Exception on /edit_profile [POST] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2022-04-03 17:22:52,152 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:29:05,331 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:31:48,361 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-03 17:35:17,798 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 00:30:04,226 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 00:31:22,975 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 00:31:43,856 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 00:34:01,490 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 00:40:09,880 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:04:49,564 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:13:28,494 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:34:00,692 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:35:26,617 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:35:45,564 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:36:14,491 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:38:52,791 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:39:18,413 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:39:39,293 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:40:08,222 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:42:20,415 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:42:32,283 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:43:38,450 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:44:26,770 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:45:58,469 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:46:14,021 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:46:43,630 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:47:06,774 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:47:16,175 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:47:43,061 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:47:55,866 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-04 23:50:05,784 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:07:06,119 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:07:10,126 ERROR: Exception on /user/ggtx [GET] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/mrprogg/flask/microblog1/app/routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mrprogg/flask/microblog1/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mrprogg/flask/microblog1/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mrprogg/flask/microblog1/app/templates/user.html", line 10, in block 'content'
    {% if user.last_seen %}<p style="font-size: 94%;">Был в сети: {{ user.last_seen|truncate(5) }}</p>{% endif %}
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/filters.py", line 870, in do_truncate
    if len(s) <= length + leeway:
TypeError: object of type 'datetime.datetime' has no len()
2022-04-05 00:09:50,734 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:10:20,749 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:12:19,263 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
